# PIPELINE DEFINITION
# Name: hf-nlp-pipeline
# Description: Pipeline for fine-tuning a Hugging Face model.
components:
  comp-deploy-component:
    executorLabel: exec-deploy-component
    inputDefinitions:
      artifacts:
        model_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-evaluate-component:
    executorLabel: exec-evaluate-component
    inputDefinitions:
      artifacts:
        model_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        metrics_output_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-preprocess-component:
    executorLabel: exec-preprocess-component
    outputDefinitions:
      artifacts:
        output_data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
  comp-train-component:
    executorLabel: exec-train-component
    inputDefinitions:
      artifacts:
        input_data_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        model_output_path:
          artifactType:
            schemaTitle: system.Artifact
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-deploy-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - deploy_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.9.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef deploy_component(model_path: Input[Artifact]):\n    import subprocess\n\
          \    subprocess.run(['python', 'deploy.py', '--model', model_path])\n\n"
        image: dwdraju/mlops:kubeflow-pipeline-v10
    exec-evaluate-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - evaluate_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.9.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef evaluate_component(model_path: Input[Artifact], metrics_output_path:\
          \ Output[Artifact]):\n    import subprocess\n    subprocess.run(['python',\
          \ 'evaluate.py', '--model', model_path, '--metrics', metrics_output_path])\n\
          \n"
        image: dwdraju/mlops:kubeflow-pipeline-v10
    exec-preprocess-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - preprocess_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.9.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef preprocess_component(output_data_path: Output[Artifact]):\n \
          \   import subprocess\n    import os\n\n    # Ensure the output directory\
          \ exists\n    os.makedirs(os.path.dirname(output_data_path), exist_ok=True)\n\
          \n    # Run the preprocess.py script, passing the output path\n    result\
          \ = subprocess.run(['python', 'preprocess.py', '--output', output_data_path])\n\
          \n    # Check if the script executed correctly\n    if result.returncode\
          \ != 0:\n        raise RuntimeError(f\"Preprocessing failed with error:\
          \ {result.stderr}\")\n\n    print(f\"Preprocessing completed. Output saved\
          \ to {output_data_path}\")\n\n"
        image: dwdraju/mlops:kubeflow-pipeline-v10
    exec-train-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.9.0'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_component(input_data_path: Input[Artifact], model_output_path:\
          \ Output[Artifact]):\n    import subprocess\n    subprocess.run(['python',\
          \ 'train.py', '--input', input_data_path, '--output', model_output_path])\n\
          \n"
        image: dwdraju/mlops:kubeflow-pipeline-v10
pipelineInfo:
  description: Pipeline for fine-tuning a Hugging Face model.
  name: hf-nlp-pipeline
root:
  dag:
    tasks:
      deploy-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-deploy-component
        dependentTasks:
        - train-component
        inputs:
          artifacts:
            model_path:
              taskOutputArtifact:
                outputArtifactKey: model_output_path
                producerTask: train-component
        taskInfo:
          name: deploy-component
      evaluate-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-evaluate-component
        dependentTasks:
        - train-component
        inputs:
          artifacts:
            model_path:
              taskOutputArtifact:
                outputArtifactKey: model_output_path
                producerTask: train-component
        taskInfo:
          name: evaluate-component
      preprocess-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-preprocess-component
        taskInfo:
          name: preprocess-component
      train-component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-component
        dependentTasks:
        - preprocess-component
        inputs:
          artifacts:
            input_data_path:
              taskOutputArtifact:
                outputArtifactKey: output_data_path
                producerTask: preprocess-component
        taskInfo:
          name: train-component
schemaVersion: 2.1.0
sdkVersion: kfp-2.9.0
